"""REST API for the WWP dashboard."""

from __future__ import annotations

from typing import Optional

from fastapi import APIRouter, File, Header, HTTPException, Query, UploadFile
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel, Field

from . import aoi as aoi_mod
from . import campaign, engine, schemes, wwpt
from .admin_units import as_tree
from .cache import ANALYSIS_CACHE, IDEMPOTENCY, TTLCache
from .geodata import PROVIDER, SEASON_IRRIGATED, SEASONS_RAINFED, YEARS

router = APIRouter()


class AnalysisRequest(BaseModel):
    aoi_type: str = Field(pattern="^(admin|polygon|upload)$")
    region: Optional[str] = None
    zone: Optional[str] = None
    woreda: Optional[str] = None
    upload_id: Optional[str] = None
    polygon: Optional[list] = None
    system: str = Field(pattern="^(rainfed|irrigated)$")
    year: str
    season: str


def _validate_season(req: AnalysisRequest):
    if req.year not in YEARS:
        raise HTTPException(422, f"Unknown year '{req.year}'.")
    valid = [SEASON_IRRIGATED] if req.system == "irrigated" else SEASONS_RAINFED
    if req.season not in valid:
        raise HTTPException(
            422, f"Season '{req.season}' is not valid for the {req.system} system."
        )


@router.get("/health")
def health():
    return {"status": "ok", "provider": PROVIDER.name,
            "synthetic": getattr(PROVIDER, "synthetic", False)}


@router.get("/admin-units")
def admin_units():
    return {"tree": as_tree(), "years": YEARS,
            "seasons": {"rainfed": SEASONS_RAINFED, "irrigated": [SEASON_IRRIGATED]}}


@router.post("/upload")
async def upload(file: UploadFile = File(...)):
    content = await file.read()
    try:
        rec = aoi_mod.register_upload(file.filename or "boundary", content)
    except aoi_mod.AOIError as e:
        raise HTTPException(422, str(e))
    feats = rec.get("features") or []
    fields = list(feats[0]["attrs"].keys()) if feats else []
    problems = wwpt.validate_features(
        [f["attrs"] for f in feats], rec.get("geometry_type", "polygon")
    )
    return {
        "upload_id": rec["upload_id"],
        "label": rec["label"],
        "bounds": rec["bounds"],
        "n_polygons": rec["n_polygons"],
        "n_features": rec["n_features"],
        "geometry_type": rec["geometry_type"],
        "crs": rec["crs"],
        "area_ha": rec["area_ha"],
        "geojson": aoi_mod.upload_geojson(rec),
        # Whether this file can drive the notebook's per-feature analysis, and
        # if not, exactly which records are short of what.
        "fields": fields,
        "scheme_ready": not problems,
        "validation": {
            "ok": not problems,
            "message": ("Data validation is successful!" if not problems
                        else "Input validation failed."),
            "problems": problems[:20],
        },
    }


@router.post("/analysis")
def analysis(req: AnalysisRequest, idempotency_key: Optional[str] = Header(default=None)):
    _validate_season(req)
    if idempotency_key:
        prior = IDEMPOTENCY.get(idempotency_key)
        if prior is not None:
            return prior
    payload = req.model_dump()
    cache_key = TTLCache.key_for(payload)
    cached = ANALYSIS_CACHE.get(cache_key)
    if cached is not None:
        result = {**cached, "cached": True}
    else:
        try:
            resolved = aoi_mod.resolve(payload)
            result = engine.run_analysis(resolved, req.system, req.year, req.season)
        except aoi_mod.AOIError as e:
            raise HTTPException(422, str(e))
        ANALYSIS_CACHE.put(cache_key, result)
    if idempotency_key:
        IDEMPOTENCY.put(idempotency_key, result)
    return result


# The generated stand-in is always offered; the campaign files are offered too
# wherever they are present. Both are loaded the same way — handed to the client
# as GeoJSON and posted back to /upload — so trying one exercises the whole
# journey rather than a shortcut through it.
GENERATED_SAMPLE = {
    "name": "generated-sample",
    "kind": "generated",
    "label": "Generated sample points",
    "note": ("Six plots in the campaign's schema, five samples each. Coordinates "
             "are approximate scheme locations, not surveyed fields."),
    "filename": "sample_irrigated_wheat_schemes.geojson",
    "geometry_type": "point",
    "n_features": len(schemes.SAMPLE_PLOTS) * 5,
    "source": "generated by this service",
}


@router.get("/schemes/datasets")
def scheme_datasets():
    """Scheme files the interface can load, ready to try the workflow with.

    The 2026 campaign shapefiles come first where this machine has them, because
    they are what the reference notebook reads; they are IWMI field data and are
    not shipped with the service, so a public deployment lists only the
    generated sample. See ``campaign.py``.
    """
    return {"datasets": campaign.available() + [GENERATED_SAMPLE]}


@router.get("/schemes/dataset")
def scheme_dataset(name: str):
    """One loadable dataset as GeoJSON, in the notebook's schema."""
    if name == GENERATED_SAMPLE["name"]:
        return {**GENERATED_SAMPLE, "geojson": schemes.sample_file()}
    try:
        return campaign.load(name)
    except aoi_mod.AOIError as e:
        raise HTTPException(404, str(e))


@router.get("/schemes/sample")
def scheme_sample():
    """The generated sample file, kept as its own endpoint.

    Served rather than shipped as a data file so it cannot drift away from the
    validator, and so no field observation leaves the campaign datasets.
    """
    return {
        "filename": GENERATED_SAMPLE["filename"],
        "geojson": schemes.sample_file(),
    }


class SchemeRequest(BaseModel):
    upload_id: str


@router.post("/schemes/analysis")
def scheme_analysis(
    req: SchemeRequest, idempotency_key: Optional[str] = Header(default=None)
):
    """Estimate every plot or sample point in an uploaded scheme file.

    This is the reference notebook's workflow: one row per feature, each over
    its own SOS/EOS window, plus the per-plot median table for point samples.
    """
    if idempotency_key:
        prior = IDEMPOTENCY.get(idempotency_key)
        if prior is not None:
            return prior
    cache_key = TTLCache.key_for({"schemes": req.upload_id})
    cached = ANALYSIS_CACHE.get(cache_key)
    if cached is not None:
        result = {**cached, "cached": True}
    else:
        try:
            result = schemes.analyse(aoi_mod.get_upload(req.upload_id))
        except aoi_mod.AOIError as e:
            raise HTTPException(422, str(e))
        ANALYSIS_CACHE.put(cache_key, result)
    if idempotency_key:
        IDEMPOTENCY.put(idempotency_key, result)
    return result


@router.get("/schemes/export/csv")
def scheme_export_csv(run_id: str, level: str = Query("features", pattern="^(features|schemes)$")):
    try:
        csv = schemes.export_csv(run_id, level)
    except aoi_mod.AOIError as e:
        raise HTTPException(404, str(e))
    name = "wwp_schemes.csv" if level == "schemes" else "wwp_features.csv"
    return PlainTextResponse(
        csv, media_type="text/csv",
        headers={"Content-Disposition": f'attachment; filename="{name}"'},
    )


@router.get("/predict")
def predict(
    lat: float = Query(ge=2, le=16), lon: float = Query(ge=32, le=49),
    system: str = "rainfed", year: str = "2024/25", season: str = "Meher",
):
    return engine.predict_point(lat, lon, system, year, season)


@router.get("/explain")
def explain(
    lat: float = Query(ge=2, le=16), lon: float = Query(ge=32, le=49),
    system: str = "rainfed", year: str = "2024/25", season: str = "Meher",
):
    return engine.explain_point(lat, lon, system, year, season)


@router.get("/export/csv")
def export_csv(run_id: str):
    try:
        csv = engine.export_csv(run_id)
    except aoi_mod.AOIError as e:
        raise HTTPException(404, str(e))
    return PlainTextResponse(
        csv, media_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="wwp_results.csv"'},
    )


@router.get("/method")
def method():
    """How the numbers are produced: equations, crop parameters, data source."""
    return {
        **wwpt.method_info(),
        "provider": PROVIDER.name,
        "synthetic": getattr(PROVIDER, "synthetic", False),
        "resolution_m": getattr(PROVIDER, "resolution_m", None),
        "seasons": {"rainfed": SEASONS_RAINFED, "irrigated": [SEASON_IRRIGATED]},
    }


@router.get("/wapor/check")
def wapor_check():
    """Verify WaPOR v3 catalogue access, mapset units and one raster read.

    Exposed because the WaPOR provider's network and unit assumptions have not
    been exercised against the live service; run this once per deployment
    before relying on its output.
    """
    from .wapor import check_access

    return check_access()
